project:
  type: book
  output-dir: docs

book:
  title: "GEOU9SP GIS Workbook"
  author: "Thiago Silva, Allan Audsley, Lindis Kipp"
  date: "08/01/2025"
  chapters:
  - index.qmd
  - part: sec_w1_intro_toGIS.qmd
    chapters:
      - lab_intro.qmd
      - lab_crs.qmd
  - part: sec_w2_vectors.qmd
    chapters:
      - lab_vectors_1.qmd
      - lab_vectors_2.qmd
  - part: sec_w3_rasters.qmd
    chapters:
      - lab_rasters_1.qmd
      - lab_rasters_2.qmd
  - part: sec_w4_cartography.qmd
    chapters:
      - lab_carto_1.qmd
      - lab_carto_2.qmd
  - part: sec_w5_spatial_analysis_I.qmd
    chapters:
      - lab_catchup1.qmd
      - lab_geoprocessing.qmd
  - part: sec_w6_spatial_analysis_II.qmd
    chapters:
      - lab_joins.qmd
      - lab_zonal.qmd
  - part: sec_w8_spatial_analysis_III.qmd
    chapters:
      - lab_dist_dens.qmd
      - lab_convex_interp.qmd
  - part: sec_w10_gnss.qmd

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt

pdf-engine: lualatex

