project:
  type: book
  output-dir: docs

book:
  title: "GEOU9SP GIS Workbook"
  author: "Thiago Silva"
  date: "24/07/2024"
  chapters:
  - index.qmd
  - part: sec_intro_toGIS.qmd
    chapters:
      - lab_intro.qmd
      - lab_crs.qmd

bibliography: references.bib

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt



