project:
  type: book
  output-dir: docs

book:
  title: "."
  author: "Norah Jones"
  date: "24/07/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt



