project:
  type: book
  output-dir: docs

book:
  title: "GEOU9SP GIS Workbook"
  author: "Thiago Silva"
  date: "24/07/2024"
  chapters:
  - index.qmd
  - part: sec_w1_intro_toGIS.qmd
    chapters:
      - lab_intro.qmd
      - lab_crs.qmd
  - part: sec_w2_vectors.qmd
    chapters:
      - lab_vectors_1.qmd
      - lab_vectors_2.qmd
  - part: sec_w3_rasters.qmd
    chapters:
      - lab_rasters_1.qmd
      - lab_rasters_2.qmd
  - part: sec_w4_cartography.qmd
  - part: sec_w5_spatial_analysis_I.qmd
    chapters:
      - lab_geoprocessing.qmd
  - part: sec_w6_spatial_analysis_II.qmd
  - part: sec_w8_spatial_analysis_III.qmd
  - part: sec_w10_gnss.qmd

format:
  html:
    theme: minty
  pdf:
    documentclass: scrreprt



