# Welcome! {.unnumbered}

This e-book was created as a lab companion for the *GEOU9SP - Geographic Information Systems* module at University of Stirling. It contains all the practical exercises that will be covered throughout the module.

This book is **not a replacement to Canvas**, so make sure you are engaging with the material on Canvas on a weekly basis!

The content of this book is organised into sections, which will correspond to the teaching weeks and practical lab sessions. You will always see the main content in the center window, with a detailed menu covering all entries in the book on the left, and a chapter-specific table of contents on the right. The Canvas pages for each lab session will always link to the corresponding chapter in this book.  

If you have any questions follow the instructions on Canvas on how to [contact the module coordinator](). 

[You can download PDf versions of each week's material from here](https://stir-my.sharepoint.com/:f:/g/personal/ala2_stir_ac_uk/EsP4F6F1Cq9AmT49tSHyTeUByKL4zoPEdZ4zvwGnJZF68A?e=77wlDJ)

