# Lab 6: The raster calculator and other rastery bits {#sec-labras2}

....

## Before you start!

1. Go through the Week 3 preparatory session on Canvas, and watch the seminar recording if you have missed it. Also make sure you have completed all labs prior to this one.

## Guided Exercise 1 




Return to the Symbology window, and expand the option Min / Max Value Settings. What is the default option selected? Experiment with the other options (with different percent clips and standard deviations) and see how the Symbology changes. Remember to Apply the changes every time you change any options.
Still, on the Symbology window, change the Classification options (drop-down menu to the left, under the classes) from Continuous to Equal Interval. To the right of it, select the number of classes as 3. Then Apply and evaluate.
Without changing your number of classes, change the Interpolation option above the classes from Linear to Discrete. Apply and evaluate. Take some time to play with these visualisation options to analyse the distribution of different Bioclimatic variables in the UK, and think about what they mean for plants, (non-human) animals and in terms of social and economic factors.
Finally, let’s work on the Symbology for the SRTM data. On the Symbology window, choose the Singleband Pseudocolor option, and then on the Color Ramp option, select Create New Color Ramp. On the small options window that comes up, select Catalog:cpt-city.
Once the catalogue window opens, go to the Topography list and select the cd-a palette. Then classify your elevation values using the User Defined Min /Max option, and type 0 as Min and 900 as Maximum. Apply and visualise. Then, before closing the Properties window, go to the Transparency table and drag the slider at the top to around 60%.

Right-click on the SRTM layer name and select Duplicate layer (this step is useful to create a copy of a layer and retain symbology. Remember, this is a temporary layer). Now, on the Symbology of the copied layer, change the render type to Hillshade. Apply and close the window. Make sure the copied layer is immediately under the original layer, and alternate each layer between on and off.

Stop and think:

What does the hillshade render style does? You may zoom in on an area of interest and examine how the topographical data appear now.
Guided Exercise 3 - Mathematical and boolean operations using the Raster CalculatorLinks to an external site.
Go to the menu Raster > Raster Calculator.... This tool allows you to apply several mathematical functions to raster layer values and even to do calculations among values.

First, find the Bio1 layer of the Bioclim raster. From the metadata, we know it is the first band, so double-click UK_bioclim@1 to add it to the expression area. In this context @1, @2, etc. indicate the respective raster band number.

As we saw above, the Bio1 layer corresponds to Annual Average Temperature, with a unit of degrees Celsius multiplied by ten. Let’s convert it to regular degree Celsius units. On the expression area, after UK_bioclim@1, use the operator /  then write 10. Then, in the top right corner, select a folder to save your file and name it appropriately (e.g. UK_bioclim_C.tif). Then click OK.

Style your new layer in the same style used for the original Bio1 layer, using the full Min / Max range, and observe the laughable maximum average temperature values for the UK (sorry, couldn't resist). Can you spot the London heat island effect (urban heat island - UHILinks to an external site.)? Can you recognise other heat islands?

Let us say we would like to relocate to the hottest (in average) locations in the UK. Go back to the raster calculator, and enter the expression UK_bioclim@1 > 100 (or use your new layer and select areas > 10). Save the result as UKs_last_hope.tif. (or more likely future_tropical_UK.tif, considering the heat waves during the last summer 2022).

Go to the Symbology layer of your newly created layer and select Paletted / Unique Values, then Classify. Then, remove the 0 values from the legend using the - (minus) button. Click on the colour box for the 1 values and select a strong red colour. Finally, go to the Transparency tab and drag the slider to around 50%. Then Apply and close the window. Position your temperature range layer just above the terrain + hillshade layers, and make sure only these three layers are visible. Pretty, isn't it?

Optional: add the UK counties layer from hereLinks to an external site.. Symbolise using "outline", no fill. Make sure the counties layer appears on the top. Can you identify the counties with the highest average temperature?



For example, let’s say we want to get the mean average annual temperature and visualize the temperature ranges for our “last hope” region only. Let us go to the Raster Calculator, and use the expression (UK_Biolcim@1 / 10) * UKs_last_hope@1. Name the resulting layer and save it, then style the result using a Pseudocolor colour ramp. However, this time manually specify the Min value as 10.  It may take a few minutes, so be patient.

Stop and think:

What happened to the temperature values when we applied the expression above? Use the information tool to probe a few values of the new raster to help you think about it.
Return to the Properties of the new masked layer, and select the Transparency tab. On the table named Transparent pixel list, click on the + (plus) button to add a new line. Fill the line with the values from = 0, to = 0 and Percent Transparent = 100. Apply and evaluate the result.
Stop and think: did you actually change the values of the raster layer when you set the transparent pixels?

Vectors can also be used as masks. Go to Raster > Extraction > Clip Raster by Mask Layer.... Select your Celsius converted average temperature raster as input layer, the gadm36_GBR_0 as your mask layer, and check the keep the resolution of the input raster box. Run the algorithm (it will take a while) then Close the window when finished. Set the transparency to 60%. Zoom to the original UK_SRTM layer extent and compare the results before and after the masking.

Now click on the menu Processing > Toolbox.... Welcome to the QGIS toolbox! You will find many additional functions here to process vectors and rasters, as well as functions from external software that can be accessed through QGIS. On the search bar at the top, search for Raster layer zonal statistics. Double-click on the tool with the name that comes up from the search. As Input layer, select the degree Celsius temperature layer you created, and as Zones layer, select the “last hope” layer (the one with the 0/1 values, not the masked temperature layer). Run (it will take a while) and then Close.




Open the attribute table of the new "statistics" layer and see what the number represents.
Independent Exercise
Is there any difference in mean values of average annual temperature between urban areas and forests in the UK? Make a map (including legend and scale) showing your results visually.

Hint 1: To ensure raster operations work properly, all rasters must be in the same projection.

Hint 2: You can also use AND and OR to create compound expressions (such as raster@1 > 20 OR raster@2 < 50) on the raster calculator (just make sure you type them in all caps).

Optional: Open a new project. Add the online Mapzen Global Elevation layer by going to the QGIS Browser and choosing XYZ Tiles > Mapzen Global Elevation, and then download the plate tectonic data from HERE Download HERE.

Image showing where to load the Mapzen layer on the QGIS Browser 

Open the properties of the DEM and select the Hillshade symbology, with a Z factor of 10. Add the earthquake and country data from Week 2. Now see if there are any clear relationships between high elevations, plate boundaries and earthquake locations.