# Week 8 - Spatial analysis III

This week, we will continue our learning of additional/advanced GIS tools. The focus for this week is on density and interpolation methods, distance calculation tools and convex hulls.

## ILOs covered

2. Obtain and assess the quality of spatial data from online and offline sources and produce new spatial data using computer and field methods;

4. Plan and execute GIS analytical steps to solve spatial problems successfully;

## What will you learn

For every week, we will list the main theoretical and practical learning goals. Use these as a 'checklist' to gauge your learning for each week. If you don't feel confident you have learned any specific topic, then revisit the week's material!

### Practical knowledge:

[@sec-spatan4]

- Density Tools
    - Kernel Density Estimation
    - Count Points in Polygons
- Distance tools
    - Distance to Nearest Hub
    - Distance Maps


[@sec-spatan5]


- Convex Hulls
- Interpolation Tools
    - Inverse Distance Weighting