# Week 4 - Making maps

This week is about visualising spatial data. For as long as Geography existed, maps have been a key way of communicating spatial information to other people. Most rules of visual design also apply to map making, but there are some additional constraints: maps need to have a proper scale, a coordinate grid (or graticule), and often a north arrow. Maps, like statistical plots, must also have a comprehensive legend, associating all visual variables present on the map to an interpretation key. Maps also often make use of textual labels to help give spatial context to the displayed information.

## ILOs covered

2.  Obtain and assess the quality of spatial data from online and offline sources and produce new spatial data using computer and field methods;

3.  Create map visualisations that adhere to cartographic principles and can be easily and unambiguously interpreted by the non-specialist public;

## What will you learn

For every week, we will list the main theoretical and practical learning goals. Use these as a 'checklist' to gauge your learning for each week. If you don't feel confident you have learned any specific topic, then revisit the week's material!

### Theoretical knowledge for Week 4:

- What is a map?
    - How is a map different from a simple figure/image?
- What are main types of maps?
- What makes a good map?
- What are visual variables?
    - What is the difference between differentiation, ordered and proportionality - variables?
    - What is perceptual equivalence in colour scales?
    - How can colour choice aid semantic interpretation?
    - How to avoid issues with colour vision deficiencies?
- What are the main cartographic elements that make a map a map?
    - What does a proper map legend consist of?
    - What is map scale?
    - What is a graticule?
- When and why to use labels on a map

### Practical knowledge:

[@sec-carto1]

- Styling rasters
    - Using built in colour palettes
- Creating a hillshade effect
- Styling line and polygon vectors
    - Using symbology presets
    - Setting custom categorized symbols
    - Creating borderless polygons
    - Copying colours between layers
- Deciding on framing, scaling and ordering of layers

[@sec-carto2]

- Adding and labelling points of interest
    - Automatic labelling
    - Manual labelling
- Adding cartographic elements
    - Legend
    - Graticule
    - Scale Bar
    - North Arrow
- Adding author and CRS information
- Exporting your map