# Week 3 - Raster data

For our third week, we will learn about the second most common data model for spatial data: raster files. While vectors are good at representing separated and/or well-defined individual regions, rasters excel at representing gradual, continuous data such as surface temperatures or elevations. 

## ILOs covered

1.  Understand the structure of spatial data and choose appropriate data types and models for storing and representing it;

2.  Obtain and assess the quality of spatial data from online and offline sources and produce new spatial data using computer and field methods;

3.  Create map visualisations that adhere to cartographic principles and can be easily and unambiguously interpreted by the non-specialist public;

4.  Plan and execute GIS analytical steps to solve spatial problems successfully;

## What will you learn

For every week, we will list the main theoretical and practical learning goals. Use these as a 'checklist' to gauge your learning for each week. If you don't feel confident you have learned any specific topic, then revisit the week's material!

### Theoretical knowledge for Week 3:

- What is the raster data model?
    - How are rasters represented?
- What are the components of a raster file (rows, columns, bands/channels, resolution)?
- What are the main raster file formats?
- What data types can rasters represent?
- What kinds of data can we represent using raster data?
- Raster / vector component equivalence
- Raster / vector tool equivalence
    - No concept of ‘ selection’ 
- What kinds of questions can we answer using rasters?
- How can we transform rasters to vectors and vice-versa
    - The concept of raster resampling
    - The concept of raster contrast manipulation

### Practical knowledge:

[@sec-labras1]

- How to identify raster files
- How to load raster files 
- How to get raster properties
- How to reproject raster data
- How to mask rasters
- How to set raster symbology
    - Continuous variables
    - Categorical variables 
- How to use the identify tool to get raster information on the fly

[@sec-labras2]

- How to calculate raster statistics 
- How to ‘select’ using the raster calculator 
    - Boolean operators on the same band
    - Boolean operators between bands
    - Band arithmetic
    - Making flowcharts
- Mosaicking rasters
- Working with Digital Elevation Models
    - Calculating slope, aspect and viewshed
- Styling raster Images 
- Resampling methods

