# Week 5 - Spatial analysis I

This week, we will get started on the 'second half' of the module, where we start to explore a variety of spatial analysis tools that extend/optimise your GIS analytical capabilities. The usual GIS workflow (get data, organise data, load data, analyse data) will remain the same, and most of the steps for the exercises from now on will still be based on the base knowledge from weeks 1-4. So it important you feel confident with these base skills before you progress with new spatial analysis tools. 

For this week, we will cover the family of geoprocessing tools.

## ILOs covered

2. Obtain and assess the quality of spatial data from online and offline sources and produce new spatial data using computer and field methods;

4. Plan and execute GIS analytical steps to solve spatial problems successfully;

## What will you learn

For every week, we will list the main theoretical and practical learning goals. Use these as a 'checklist' to gauge your learning for each week. If you don't feel confident you have learned any specific topic, then revisit the week's material!

### Practical knowledge:

[@sec-catch1]

No new knowledge for this section - it is reserved for you to catch up with previoous content

[@sec-spatan1]

- Geoprocessing tools
    - Clip vs Intersection
    - Union
    - Difference and Symmetrical Difference
    - Dissolve
    - Buffers