# Week 1 - Introduction

In our first week, we will get acquainted to with basic GIS data manipulation using the QGIS software.

## ILOs covered

1.  Understand the structure of spatial data and choose appropriate data types and models for storing and representing it;

2.  Obtain and assess the quality of spatial data from online and offline sources and produce new spatial data using computer and field methods;

3.  Create map visualisations that adhere to cartographic principles and can be easily and unambiguously interpreted by the non-specialist public;

## What will you learn

For every week, we will list the main theoretical and practical learning goals. Use these as a 'checklist' to gauge your learning for each week. If you don't feel confident you have learned any specific topic, then revisit the week's material!

### Theoretical knowledge for Week 1:

- What are Geomatics, GIS, Remote Sensing and associated terms and fields?
- What is spatial data?
- What is a datum?
- What is a map projection?
- What is a Coordinate Reference System?

### Practical knowledge:

[@sec-exoverview]

-   How to launch QGIS
-   How to load a spatial data file
-   How to navigate the main QGIS interface
-   How to identify features
-   How to do basic measurements
-   How to do basic styling of spatial data
-   How to enter the layout editor
-   How to make and export a simple map layout

[@sec-excrs]

-   How to check the Coordinate Reference System of a spatial file
-   How to set the CRS of a QGIS project
-   How to set the CRS of a spatial file when it is already known.
-   How to reproject(convert) a spatial file from one CRS to another
-   What are the main CRSs you should be familiar with.
